export const WALLETS = Object.freeze({
  PORTIS: 'PORTIS',
  METAMASK: 'METAMASK',
  WALLETCONNECT: 'WALLET_CONNECT'
})

export const CONNECTORS_ERROR = Object.freeze({
  NOT_SUPPORTED_NETWORK:
    "Network not supported! Please change your wallet's network and try again.",
  NOT_SUPPORTED_WALLET: 'Wallet not supported!',
  WRONG_SIGNATURE: 'Wrong signature! Please refresh and try again.',
  GENERIC_ERROR: 'Something went wrong! Please try again.',
  NO_CACHED_CONNECTION: 'Sign in again!'
})

export const NETWORK_NAMES = Object.freeze({
  MAINNET: 'MAINNET',
  ROPSTEN: 'ROPSTEN',
  RINKEBY: 'RINKEBY',
  GOERLI: 'GOERLI',
  MUMBAI: 'MUMBAI',
  KOVAN: 'KOVAN'
})

export const CHAIN_IDS = Object.freeze({
  MAINNET_ID: 1,
  ROPSTEN_ID: 3,
  RINKEBY_ID: 4,
  GOERLI_ID: 5,
  KOVAN_ID: 42,
  MUMBAI_ID: 80001
})

export const networkNameToIdLookup = {
  [NETWORK_NAMES.MAINNET]: CHAIN_IDS.MAINNET_ID,
  [NETWORK_NAMES.ROPSTEN]: CHAIN_IDS.ROPSTEN_ID,
  [NETWORK_NAMES.KOVAN]: CHAIN_IDS.KOVAN_ID,
  [NETWORK_NAMES.RINKEBY]: CHAIN_IDS.RINKEBY_ID,
  [NETWORK_NAMES.GOERLI]: CHAIN_IDS.GOERLI_ID,
  [NETWORK_NAMES.MUMBAI]: CHAIN_IDS.MUMBAI_ID
}

export const CHAIN_ID_TO_NETWORK_NAME = {
  1: NETWORK_NAMES.MAINNET,
  3: NETWORK_NAMES.ROPSTEN,
  4: NETWORK_NAMES.RINKEBY,
  5: NETWORK_NAMES.GOERLI,
  42: NETWORK_NAMES.KOVAN,
  80001: NETWORK_NAMES.MUMBAI
}
