const LOCAL_STORAGE_NAMESPACE = 'CROWDCLICK'
export const SCOPED_LOCAL_STORAGE_CHAIN_ID = `${LOCAL_STORAGE_NAMESPACE}::CROWDCLICK_CHAINID`
export const SCOPED_LOCAL_STORAGE_USER_PUBLIC_KEY = `${LOCAL_STORAGE_NAMESPACE}::USER_PUBLIC_KEY`
