const IS_LOADING_COMPLETED_ACTION = 'LOADING_COMPLETED'
const CURRENT_SECOND_ACTION = 'CURRENT_SECOND'
const TASK_INTERRUPTIONS_ACTION = 'TASK_INTERRUPTIONS'
const IS_TASK_STOPPED_TRUE_ACTION = 'TASK_INTERRUPTED'
const IS_TASK_STOPPED_FALSE_ACTION = 'TASK_RESUMED'
const WAS_TASK_SUCCESSFUL_TRUE_ACTION = 'TASK_SUCCESSFUL'
const WAS_TASK_SUCCESSFUL_FALSE_ACTION = 'TASK_FAILED'

const initialState = {
  isLoading: true,
  currentSecond: 1,
  taskInterruptions: 0,
  isTaskStopped: false,
  wasTaskSuccessful: null
}

const taskState = {
  IS_LOADING_COMPLETED_ACTION,
  CURRENT_SECOND_ACTION,
  TASK_INTERRUPTIONS_ACTION,
  IS_TASK_STOPPED_TRUE_ACTION,
  IS_TASK_STOPPED_FALSE_ACTION,
  WAS_TASK_SUCCESSFUL_TRUE_ACTION,
  WAS_TASK_SUCCESSFUL_FALSE_ACTION,
  initialState
}

export default taskState
